services:
  api-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE}
        GIT_SHA: ${GIT_SHA}
        GIT_BRANCH: ${GIT_BRANCH}
    env_file:
      - .env
      - .env.example
    ports:
      - "${APP_PORT-8001}:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:${APP_PORT:-8001}/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

  api-pi:
    profiles: ["pi"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE}
        GIT_SHA: ${GIT_SHA}
        GIT_BRANCH: ${GIT_BRANCH}
    env_file:
      - .env
      - .env.example
    ports:
      - "${APP_PORT-8001}:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:${APP_PORT:-8001}/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
