version: "3.9"

# Optional: a reusable logging config for tidy JSON logs
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  # ------------------------------
  # FastAPI service (existing app)
  # ------------------------------
  api:
    build: .
    container_name: persona-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "${API_PORT:-8001}:8001"
    env_file:
      - .env.example
    environment:
      APP_ENV: "dev"
      # Keep SQLite on a writable volume path
      DB_PATH: "${DB_PATH:-/data/engagement.db}"
    volumes:
      - ./data:/data:rw
    # Healthcheck uses /ready now (simpler & aligned with readiness gate)
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      worker:
        condition: service_started
    restart: unless-stopped
    logging: *default-logging
    # Harden runtime: readonly root FS with tmpfs scratch
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    networks:
      - appnet

  # --------------------------------------
  # Background worker with HTTP health
  # --------------------------------------
  worker:
    image: python:3.11-slim
    container_name: persona-worker
    working_dir: /app
    volumes:
      - .:/app:ro
    command: ["python", "-m", "app.worker.health_srv"]
    ports:
      - "8022:8022"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport urllib.request,sys\ntry:\n  urllib.request.urlopen('http://localhost:8022/health',timeout=2).read(); print('ok')\nexcept Exception as e:\n  print(e); sys.exit(1)\nPY"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging: *default-logging
    # Optional hardening for worker, too
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    networks:
      - appnet

  # ---------------------------------------------------------
  # Monitoring placeholder (Nginx stand-in until we add real)
  # Exposed on :8090 to avoid clashes with other stacks.
  # ---------------------------------------------------------
  monitor:
    image: nginx:alpine
    container_name: persona-monitor
    profiles: ["monitoring"]
    ports:
      - "8090:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    logging: *default-logging
    networks:
      - appnet

  # ---------------------------------------------------------
  # Test runner (one-shot pytest) — run with: make test
  # ---------------------------------------------------------
  test:
    image: python:3.11-slim
    container_name: persona-test
    profiles: ["test"]
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    command: >
      sh -c "
        python -m pip install --quiet --upgrade pip &&
        pip install --quiet -r requirements.txt 2>/dev/null || true &&
        pip install --quiet -r requirements-dev.txt 2>/dev/null || true &&
        pip install --quiet pytest &&
        pytest -q --disable-warnings -x
      "
    networks:
      - appnet

# Named network so services can talk by name (api ↔ worker ↔ monitor ↔ test)
networks:
  appnet:
    driver: bridge
