[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# include import sorting ("I") and your existing rule sets
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E501"]  # Black handles long lines
