apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: persona-lab
  labels:
    app: persona-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: persona-lab
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
