apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persona-lab-data
  labels:
    app: persona-lab
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
