name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest

      - name: Run pytest
        run: pytest -q --disable-warnings -x

  compose-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      docker:
        image: docker:dind
        # dind provided automatically on ubuntu-latest; this service block is optional
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Compose up (api + worker only)
        run: docker compose up -d

      - name: Wait for API health
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:8001/health >/dev/null 2>&1; then
              echo "API healthy ✅"; exit 0
            fi
            sleep 1
          done
          echo "API failed to become healthy ❌"; docker compose logs --no-color api; exit 1

      - name: Check Worker health
        run: |
          curl -fsS http://localhost:8022/health >/dev/null
          echo "Worker healthy ✅"

      - name: Teardown
        if: always()
        run: docker compose down --remove-orphans
